apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
data:
  kong.yml: |
    _format_version: "3.0"
    _transform: true

    services:
    - name: carpark-api
      url: http://promjodd-{{ .Values.envAlias }}-carpark-api/
      routes:
      - name: carpark-api
        strip_path: true
        paths:
        - /

    plugins:
    - name: http-log
      service: SERVICE_NAME|SERVICE_ID
      config:
        http_endpoint: http://promjodd-{{ .Values.envAlias }}-telegraf/telegraf
        method: POST
        timeout: 1000
        keepalive: 1000
        flush_timeout: 2
        retry_count: 15
