apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgadmin-ing
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Scheme $scheme;
      proxy_set_header Host $host;
      proxy_pass http://localhost:5050/;
      proxy_redirect off;
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - {{ .Values.domainPgAdmin }}
      secretName: pgadmin-cert
  rules:
    - host: {{ .Values.domainPgAdmin }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: promjodd-{{ .Values.envAlias }}-pgadmin4
                port:
                  number: 80
